### ISSUE TITLE
Set up nextcloud on the NUC

### ISSUE THREAD

**Issue by Aephir** [Aephir/Home_Assistant#2]
https://github.com/nextcloud/docker

Give it a try, but will probably not be that interesting until I get serious amounts of SSD.

**Comment by Aephir** [comment]
https://github.com/nextcloud/docker

docker-compose (for v2, will it work?). Need to also have mariadb set up
```
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:  
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
```
