### ISSUE TITLE
Telegram actionable notifications in AppDaemon

### ISSUE THREAD

**Issue by Aephir** [Aephir/Home_Assistant#37]
https://community.home-assistant.io/t/telegram-actionable-notifications-help/95267/10

How to translate?

https://github.com/Aephir/Home_Assistant/blob/master/appdaemon/apps/telegram/telegram_callback.py

**Comment by Aephir** [comment]
I have all the actionable notifications set up, but I can't get this:

```yaml
- id: 'telegramremoveinline' # https://community.home-assistant.io/t/telegram-bot-notifications-and-communication/50247
  alias: 'Telegram callback to remove keyboard'
  hide_entity: true
  initial_state: True
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/removekeyboard'
  action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: 'OK'
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.user_id }}'
      inline_keyboard: []
```

translated to something in AppDaemon (python).
